remove the --aggressive flag of git gc
The server is no longer able to cope with this flag, it constantly fails:

Checking connectivity: 678136, done.
Counting objects: 678136, done.
error: pack-objects died of signal 9736)
error: failed to run repack

Let's see if a regular daily gc is enough.